---

- name: copy svacer to VM
  ansible.builtin.copy:
    src: ~/forsonas/svacer/{{ svacer_version }}
    dest: "{{ tools_dir }}"
    remote_src: yes
    owner: root
    group: root
    mode: '755'
    
- name: unpacking svacer
  ansible.builtin.shell:
    cmd: |
      mkdir -p "{{ svacer_dir }}"
      tar -xzf ~/tools/svacer*.tar.gz --strip-components=1 -C /opt/svacer
    creates: /opt/svacer/bin/svacer

- name: add svacer to PATH
  ansible.builtin.copy:
    dest: /usr/local/bin/svacer
    content: |
      #!/bin/bash
      "{{ svacer_dir }}"/bin/svacer "$@"
    mode: '0755'
    owner: root
    group: root
  #become: yes