---

- name: copy svace to VM
  ansible.builtin.copy:
    src: ~/forsonas/svace/{{ svace_version }}
    dest: "{{ tools_dir }}"
    remote_src: yes
    owner: root
    group: root
    mode: '755'
    
- name: unpacking svace
  ansible.builtin.shell: |
    mkdir -p "{{ svace_dir }}"
    tar -xjf ~/tools/svace*.tar.bz2 --strip-components=1 -C /opt/svace
  creates: /opt/svace/bin/svace

- name: add svace to PATH
  ansible.builtin.copy:
    dest: /usr/local/bin/svace
    content: |
      #!/bin/bash
      "{{ svace_dir }}"/bin/svace "$@"
    mode: '0755'
    owner: root
    group: root
  #become: yes