---

- name: install unzip
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: yes
  become: yes

- name: copy sonar-scanner-cli to VM
  ansible.builtin.copy:
    src: ~/forsonas/sonar-scanner-cli/{{ sonar_scanner_cli_version }}
    dest: "{{ tools_dir }}"
    remote_src: yes
    owner: root
    group: root
    mode: '755'

- name: unpacking sonar-scanner-cli
  ansible.builtin.unarchive:
    src: "{{ tools_dir }}/{{ sonar_scanner_cli_version }}"
    dest: /opt
    remote_src: yes
    owner: root
    group: root
    mode: '0755'

- name: find extracted directory
  ansible.builtin.find:
    paths: /opt
    pattern: "sonar-scanner-*"
    file_type: directory
  register: sonar_dir

- name: remove existing symlink or directory (if any)
  ansible.builtin.file:
    path: "{{ dir_for_sonar_scanner_cli }}"
    state: absent
  when: sonar_dir.files | length > 0

- name: create symlink to versioned folder
  ansible.builtin.file:
    src: "{{ sonar_dir.files[0].path }}"
    dest: "{{ dir_for_sonar_scanner_cli }}"
    state: link
    owner: root
    group: root

- name: add sonar-scanner-cli to PATH
  ansible.builtin.copy:
    dest: /usr/local/bin/sonar-scanner
    content: |
      #!/bin/bash
      "{{ dir_for_sonar_scanner_cli }}"/bin/sonar-scanner "$@"
    mode: '0755'
    owner: root
    group: root
  #become: yes