---

- name: install unzip
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: yes
  become: yes

- name: copy sonar-scanner-cli to VM
  ansible.builtin.copy:
    src: ~/forsonas/sonar-scanner-cli/{{ sonar_scanner_cli_version }}
    dest: "{{ tools_dir }}"
    remote_src: yes
    owner: root
    group: root
    mode: '755'
    
- name: make dir sonar-scanner-cli
  ansible.builtin.file:
    path: "{{ dir_for_sonar_scanner_cli }}"
    state: directory
    mode: '0755'
    owner: root
    group: root 

- name: unpacking sonar-scanner-cli
  ansible.builtin.unarchive:
    src: "{{ tools_dir }}/{{ sonar_scanner_cli_version }}"
    dest: /opt
    remote_src: yes
    owner: root
    group: root
    mode: '0755'

- name: create symlink to versioned folder
  ansible.builtin.file:
    src: "/opt/{{ sonar_scanner_cli_version | replace('.zip','') | replace('sonar-scanner-cli','sonar-scanner') }}"
    dest: "{{ dir_for_sonar_scanner_cli }}"
    state: link
    owner: root
    group: root

- name: add sonar-scanner-cli to PATH
  ansible.builtin.copy:
    dest: /usr/local/bin/sonar-scanner-cli
    content: |
      #!/bin/bash
      "{{ dir_for_sonar_scanner_cli }}"/bin/sonar-scanner "$@"
    mode: '0755'
    owner: root
    group: root
  #become: yes