---

- name: prepare env on vm for analyze
  hosts: vm
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: installing cifs-utils
      apt:
        name: cifs-utils
        state: present
        update_cache: yes
    
    - name: make dir tools
      ansible.builtin.file:
        path: ~/tools
        state: directory
        mode: '0755'
        owner: root
        group: root
    
    - name: make dir forsonas
      ansible.builtin.file:
        path: ~/forsonas
        state: directory
        mode: '0755'
        owner: root
        group: root 
    
    - name: forsonas mount
      ansible.posix.mount:
        path: ~/forsonas
        src: //192.168.25.230/программное_обеспечение/venv/jenkins-env
        fstype: cifs
        opts: "username=kirill_v,password=komusfanvil"
        state: mounted       

    - name: copy svace to VM
      ansible.builtin.copy:
        src: ~/forsonas/svace/{{ svace_version }}
        dest: ~/tools
        remote_src: yes
        owner: root
        group: root
        mode: '755'

    - name: UNMOUNT forsonas
      ansible.posix.mount:
        path: ~/forsonas
        state: unmounted