---

- name: prepare env on vm for analyze
  hosts: vm
  become: true
  vars_files:
    - vars.yml

  roles:
    - role: mount_share
      tages:
        - analyze
        - installation
    - role: install_svace
      tages:
        - svace

  tasks:
#### Подготовка к подключению диска ####
         

### SVACE STAGE ####
    

### UNMOUNT FORSONAS ###

    - name: UNMOUNT forsonas
      ansible.posix.mount:
        path: "{{ dir_for_forsonas }}"
        state: unmounted